name: crimson_test
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  crimson:
    path: ../
  intl: ^0.17.0
  json_serializable: ^6.5.4
  build_runner: 2.3.3
  test: ^1.22.1
  freezed_annotation: ^2.2.0
  dart_json_mapper: ^2.2.7
  freezed: ^2.3.2
